language: node_js
node_js:
  - "5"
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - PUBLIC_PATH=/webpack-slides/ npm run build
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - bash ./deploy-gh-pages.sh
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"